/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oodjasssignment;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AdminInterface extends javax.swing.JFrame {
    Admin admin = new Admin();
    User user = new User();
    String productID,productName,productFrag,productPrice,productQuan;
    /** Creates new form AdminInterface */
    public AdminInterface() {
        initComponents();
        ViewCusTable.setModel(new DefaultTableModel(null,new String []{"Name", "Password","Email","Address","Phone Number"}));
        ViewProdTable.setModel(new DefaultTableModel(null,new String []{"Product ID", "Product Name","Fragile","Price","Quantity"}));

        admin.viewTable(ViewCusTable,"Customer.txt");
        admin.viewTable(ViewProdTable,"Product.txt");
        admin.viewTable(ViewOrderTable,"Order.txt");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profile = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AdminName = new javax.swing.JTextField();
        AdminEmail = new javax.swing.JTextField();
        AdminPhone = new javax.swing.JTextField();
        AdminAddress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewProdTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addProdID = new javax.swing.JTextField();
        addProdName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addProdPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addProdQuan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CancelProdBtn = new javax.swing.JButton();
        AddProdBtn = new javax.swing.JButton();
        DelProdBtn = new javax.swing.JButton();
        UpdateProdBtn = new javax.swing.JButton();
        FragileCheck = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        searchProd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewCusTable = new javax.swing.JTable();
        AddCusName = new javax.swing.JTextField();
        addCusAddress = new javax.swing.JTextField();
        AddCusEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CancelProdBtn1 = new javax.swing.JButton();
        AddCusBtn = new javax.swing.JButton();
        DelCusBtn = new javax.swing.JButton();
        UpdateCusBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        AddCusPassw = new javax.swing.JTextField();
        AddCusPhone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        SearchCus = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        AdmCusOrderTable = new javax.swing.JScrollPane();
        ViewOrderTable = new javax.swing.JTable();
        ViewOrder = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        SelectedId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        SearchOrder = new javax.swing.JTextField();
        LogoutLbl = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Profile.setToolTipText("");
        Profile.setName(""); // NOI18N

        jLabel11.setText("Name");

        jLabel12.setText("Phone Number");

        jLabel13.setText("Email");

        jLabel14.setText("Address");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(129, 129, 129)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AdminPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AdminAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        Profile.addTab("Profile", jPanel3);

        ViewProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Fragile", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewProdTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewProdTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ViewProdTable);
        if (ViewProdTable.getColumnModel().getColumnCount() > 0) {
            ViewProdTable.getColumnModel().getColumn(0).setResizable(false);
            ViewProdTable.getColumnModel().getColumn(1).setResizable(false);
            ViewProdTable.getColumnModel().getColumn(2).setResizable(false);
            ViewProdTable.getColumnModel().getColumn(3).setResizable(false);
            ViewProdTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Add Product ID : ");

        jLabel2.setText("Add Product Name : ");

        addProdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdPriceActionPerformed(evt);
            }
        });
        addProdPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addProdPriceKeyTyped(evt);
            }
        });

        jLabel3.setText("Add Price : ");

        addProdQuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addProdQuanKeyTyped(evt);
            }
        });

        jLabel4.setText("Add Quantity");

        CancelProdBtn.setText("Clear");

        AddProdBtn.setText("Add");
        AddProdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProdBtnMouseClicked(evt);
            }
        });

        DelProdBtn.setText("Delete");
        DelProdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelProdBtnMouseClicked(evt);
            }
        });

        UpdateProdBtn.setText("Update");
        UpdateProdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateProdBtnMouseClicked(evt);
            }
        });
        UpdateProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProdBtnActionPerformed(evt);
            }
        });

        FragileCheck.setText("Check If Yes");

        jLabel10.setText("Is It Fragile? : ");

        jLabel16.setText("Search : ");

        searchProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchProdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(addProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addProdName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FragileCheck, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addProdQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(UpdateProdBtn)
                        .addGap(18, 18, 18)
                        .addComponent(AddProdBtn)
                        .addGap(18, 18, 18)
                        .addComponent(CancelProdBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DelProdBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchProd, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(searchProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(addProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddProdBtn)
                        .addComponent(CancelProdBtn)
                        .addComponent(UpdateProdBtn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(addProdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addProdQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FragileCheck)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(DelProdBtn)
                .addContainerGap())
        );

        Profile.addTab("products", jPanel1);

        ViewCusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Password", "Email", "Address", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewCusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCusTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ViewCusTable);
        if (ViewCusTable.getColumnModel().getColumnCount() > 0) {
            ViewCusTable.getColumnModel().getColumn(0).setResizable(false);
            ViewCusTable.getColumnModel().getColumn(1).setResizable(false);
            ViewCusTable.getColumnModel().getColumn(2).setResizable(false);
            ViewCusTable.getColumnModel().getColumn(3).setResizable(false);
            ViewCusTable.getColumnModel().getColumn(4).setResizable(false);
        }

        AddCusEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCusEmailActionPerformed(evt);
            }
        });

        jLabel5.setText("Email : ");

        jLabel6.setText("Address : ");

        jLabel7.setText("Phone Number : ");

        jLabel8.setText("Name : ");

        CancelProdBtn1.setText("Cancel");

        AddCusBtn.setText("Add");
        AddCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCusBtnMouseClicked(evt);
            }
        });

        DelCusBtn.setText("Delete");
        DelCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelCusBtnMouseClicked(evt);
            }
        });

        UpdateCusBtn.setText("Update");
        UpdateCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateCusBtnMouseClicked(evt);
            }
        });

        jLabel9.setText("Password : ");

        AddCusPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddCusPhoneKeyTyped(evt);
            }
        });

        jLabel17.setText("Search : ");

        SearchCus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchCusKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(AddCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(AddCusPassw, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddCusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addCusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddCusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(UpdateCusBtn)
                                .addGap(18, 18, 18)
                                .addComponent(AddCusBtn)
                                .addGap(18, 18, 18)
                                .addComponent(CancelProdBtn1))
                            .addComponent(DelCusBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchCus, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(SearchCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddCusBtn)
                            .addComponent(CancelProdBtn1)
                            .addComponent(UpdateCusBtn))
                        .addGap(47, 47, 47)
                        .addComponent(DelCusBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddCusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(AddCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(AddCusPassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddCusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap())))
        );

        Profile.addTab("customers", jPanel2);

        ViewOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Order ID", "total(RM)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewOrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewOrderTableMouseClicked(evt);
            }
        });
        AdmCusOrderTable.setViewportView(ViewOrderTable);
        if (ViewOrderTable.getColumnModel().getColumnCount() > 0) {
            ViewOrderTable.getColumnModel().getColumn(0).setResizable(false);
            ViewOrderTable.getColumnModel().getColumn(1).setResizable(false);
            ViewOrderTable.getColumnModel().getColumn(2).setResizable(false);
        }

        ViewOrder.setText("VIew Order");
        ViewOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewOrderMouseClicked(evt);
            }
        });

        jLabel15.setText("selected OrderId : ");

        jLabel18.setText("Search : ");

        SearchOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchOrderKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(AdmCusOrderTable, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(SelectedId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewOrder)
                        .addGap(125, 125, 125))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(SearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdmCusOrderTable, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ViewOrder))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(SelectedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        SelectedId.setEditable(false);

        Profile.addTab("orders", panel1);

        LogoutLbl.setAlignment(java.awt.Label.CENTER);
        LogoutLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LogoutLbl.setForeground(new java.awt.Color(51, 102, 255));
        LogoutLbl.setText("Logout");
        LogoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LogoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Profile)
                .addContainerGap())
        );

        LogoutLbl.getAccessibleContext().setAccessibleName("AdminLogoutLbl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProdPriceActionPerformed

    private void AddCusEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCusEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCusEmailActionPerformed

    private void UpdateProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProdBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProdBtnActionPerformed

    private void AddProdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProdBtnMouseClicked
        // TODO add your handling code here:
        String ProdId = this.addProdID.getText();
        String ProdName = this.addProdName.getText();
        boolean Fragile = this.FragileCheck.isSelected();
        String FragileChecks;
        if (Fragile){
            FragileChecks = "Fragile";
        }else{
            FragileChecks = "NonFragile";
        }
        String ProdPrice = this.addProdPrice.getText();
        String ProdQuan = this.addProdQuan.getText();
        if (addProdID.getText().isEmpty()||addProdName.getText().isEmpty()||addProdPrice.getText().isEmpty()||addProdQuan.getText().isEmpty())
        {
        JOptionPane.showMessageDialog(null,
                        "Some Fields Are Empty", "Error",
                        JOptionPane.INFORMATION_MESSAGE);
        }else{
        admin.addProd(ProdId,ProdName,FragileChecks,ProdPrice,ProdQuan);
        
        addProdID.setText("");
        addProdName.setText("");
        FragileCheck.setSelected(false);
        addProdPrice.setText("");
        addProdQuan.setText("");
        
        ViewProdTable.setModel(new DefaultTableModel(null,new String []{"Product ID", "Product Name","Fragile","Price","Quantity"}));

        admin.viewTable(ViewProdTable,"Product.txt");
        }
        
    }//GEN-LAST:event_AddProdBtnMouseClicked

    private void AddCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCusBtnMouseClicked
        // TODO add your handling code here:
        String CusName = this.AddCusName.getText();
        String CusPass = this.AddCusPassw.getText();
        String CusEmail = this.AddCusEmail.getText();
        String CusAdd = this.addCusAddress.getText();
        String CusPhone = this.AddCusPhone.getText();
        if (AddCusName.getText().isEmpty()||AddCusPassw.getText().isEmpty()||AddCusEmail.getText().isEmpty()||addCusAddress.getText().isEmpty()||AddCusPhone.getText().isEmpty())
        {
        JOptionPane.showMessageDialog(null,
                        "Some Fields Are Empty", "Error",
                        JOptionPane.INFORMATION_MESSAGE);
        }else{
        admin.addCus(CusName, CusPass, CusEmail, CusAdd, CusPhone);
        JOptionPane.showMessageDialog(null,
                        "Record Added Successfully", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
        AddCusName.setText("");
        AddCusPassw.setText("");
        AddCusEmail.setText("");
        addCusAddress.setText("");
        AddCusPhone.setText("");
        ViewCusTable.removeAll();
        ViewCusTable.setModel(new DefaultTableModel(null,new String []{"Name", "Password","Email","Address","Phone Number"}));

        admin.viewTable(ViewCusTable,"Customer.txt");
        
        }
    }//GEN-LAST:event_AddCusBtnMouseClicked

    private void AddCusPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddCusPhoneKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
            
        }
    }//GEN-LAST:event_AddCusPhoneKeyTyped

    private void addProdPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addProdPriceKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isAlphabetic(c)){
            evt.consume();
        }
    }//GEN-LAST:event_addProdPriceKeyTyped

    private void addProdQuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addProdQuanKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
            
        }
    }//GEN-LAST:event_addProdQuanKeyTyped

    private void ViewProdTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProdTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel ProdsTable = (DefaultTableModel)ViewProdTable.getModel();
         productID = ProdsTable.getValueAt(ViewProdTable.getSelectedRow(),0).toString();
         productName = ProdsTable.getValueAt(ViewProdTable.getSelectedRow(),1).toString();
         productFrag = ProdsTable.getValueAt(ViewProdTable.getSelectedRow(),2).toString();
         productPrice = ProdsTable.getValueAt(ViewProdTable.getSelectedRow(),3).toString();
         productQuan = ProdsTable.getValueAt(ViewProdTable.getSelectedRow(),4).toString();
        addProdID.setText(productID);
        addProdName.setText(productName);
        switch(productFrag){
            case "Fragile":
                FragileCheck.setSelected(true);
                break;
            case "NonFragile":
                FragileCheck.setSelected(false);
                break;
            default:
                FragileCheck.setSelected(false);
                break;
        }
        addProdPrice.setText(productPrice);
        addProdQuan.setText(productQuan);
        
        
    }//GEN-LAST:event_ViewProdTableMouseClicked

    private void ViewCusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCusTableMouseClicked
        // TODO add your handling code here:
        try {
        DefaultTableModel CusTable = (DefaultTableModel)ViewCusTable.getModel();
        String CustomerID = CusTable.getValueAt(ViewCusTable.getSelectedRow(),0).toString();
        String CustomerPass = CusTable.getValueAt(ViewCusTable.getSelectedRow(),1).toString();
        String  CustomerEmail= CusTable.getValueAt(ViewCusTable.getSelectedRow(),2).toString();
        String CustomerAddress = CusTable.getValueAt(ViewCusTable.getSelectedRow(),3).toString();
        String CustomerPhone = CusTable.getValueAt(ViewCusTable.getSelectedRow(),4).toString();
        AddCusName.setText(CustomerID);
        AddCusPassw.setText(CustomerPass);
        
        AddCusEmail.setText(CustomerEmail);
        addCusAddress.setText(CustomerAddress);
        AddCusPhone.setText(CustomerPhone);
        }
        catch(java.lang.NullPointerException n) {
        JOptionPane.showMessageDialog(null,
                        "please select a row", "Error",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ViewCusTableMouseClicked

    private void DelProdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelProdBtnMouseClicked
        // TODO add your handling code here:
        admin.deleteItems(ViewProdTable, "Product.txt");
        addProdID.setText("");
        addProdName.setText("");
        FragileCheck.setSelected(false);
        addProdPrice.setText("");
        addProdQuan.setText("");
        ViewProdTable.setModel(new DefaultTableModel(null,new String []{"Product ID", "Product Name","Fragile","Price","Quantity"}));

        admin.viewTable(ViewProdTable,"Product.txt");
    }//GEN-LAST:event_DelProdBtnMouseClicked

    private void DelCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelCusBtnMouseClicked
        // TODO add your handling code here:
        admin.deleteItems(ViewCusTable, "Customer.txt");
        AddCusName.setText("");
        AddCusPassw.setText("");
        AddCusEmail.setText("");
        addCusAddress.setText("");
        AddCusPhone.setText("");
        ViewCusTable.setModel(new DefaultTableModel(null,new String []{"Name", "Password","Email","Address","Phone Number"}));

        admin.viewTable(ViewCusTable,"Customer.txt");
    }//GEN-LAST:event_DelCusBtnMouseClicked

    private void UpdateProdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProdBtnMouseClicked
        // TODO add your handling code here:
        
        admin.exportChanges(ViewProdTable,"Product.txt");
        
        ViewProdTable.setModel(new DefaultTableModel(null,new String []{"Product ID", "Product Name","Fragile","Price","Quantity"}));

        admin.viewTable(ViewProdTable,"Product.txt");
    }//GEN-LAST:event_UpdateProdBtnMouseClicked

    private void ViewOrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewOrderTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel CusTable = (DefaultTableModel)ViewOrderTable.getModel();
        String CustomerID = CusTable.getValueAt(ViewOrderTable.getSelectedRow(),0).toString();
        String OrderId = CusTable.getValueAt(ViewOrderTable.getSelectedRow(),1).toString();
        String  Total= CusTable.getValueAt(ViewOrderTable.getSelectedRow(),2).toString();
        
        SelectedId.setText(OrderId);
        
    }//GEN-LAST:event_ViewOrderTableMouseClicked

    private void ViewOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewOrderMouseClicked
        // TODO add your handling code here:
       
        viewOrderAdm viewOrders = new viewOrderAdm();
        viewOrders.OrderIdView.setText(SelectedId.getText());
        viewOrders.setVisible(true);
    }//GEN-LAST:event_ViewOrderMouseClicked

    private void LogoutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLblMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_LogoutLblMouseClicked

    private void UpdateCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateCusBtnMouseClicked
        // TODO add your handling code here:
        admin.exportChanges(ViewCusTable,"Customer.txt");
    }//GEN-LAST:event_UpdateCusBtnMouseClicked

    private void SearchCusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchCusKeyReleased
        // TODO add your handling code here:
        String searchItem = SearchCus.getText();
        admin.filter(ViewCusTable, searchItem);
    }//GEN-LAST:event_SearchCusKeyReleased

    private void searchProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchProdKeyReleased
        // TODO add your handling code here:
        String searchItem = searchProd.getText();
        admin.filter(ViewProdTable, searchItem);
    }//GEN-LAST:event_searchProdKeyReleased

    private void SearchOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchOrderKeyReleased
        // TODO add your handling code here:
        String searchItem = SearchOrder.getText();
        admin.filter(ViewOrderTable, searchItem);
    }//GEN-LAST:event_SearchOrderKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCusBtn;
    private javax.swing.JTextField AddCusEmail;
    private javax.swing.JTextField AddCusName;
    private javax.swing.JTextField AddCusPassw;
    private javax.swing.JTextField AddCusPhone;
    private javax.swing.JButton AddProdBtn;
    private javax.swing.JScrollPane AdmCusOrderTable;
    public javax.swing.JTextField AdminAddress;
    public javax.swing.JTextField AdminEmail;
    public javax.swing.JTextField AdminName;
    public javax.swing.JTextField AdminPhone;
    private javax.swing.JButton CancelProdBtn;
    private javax.swing.JButton CancelProdBtn1;
    private javax.swing.JButton DelCusBtn;
    private javax.swing.JButton DelProdBtn;
    private javax.swing.JCheckBox FragileCheck;
    private java.awt.Label LogoutLbl;
    private javax.swing.JTabbedPane Profile;
    private javax.swing.JTextField SearchCus;
    private javax.swing.JTextField SearchOrder;
    public static javax.swing.JTextField SelectedId;
    private javax.swing.JButton UpdateCusBtn;
    private javax.swing.JButton UpdateProdBtn;
    private javax.swing.JTable ViewCusTable;
    private javax.swing.JButton ViewOrder;
    public javax.swing.JTable ViewOrderTable;
    private javax.swing.JTable ViewProdTable;
    private javax.swing.JTextField addCusAddress;
    private javax.swing.JTextField addProdID;
    private javax.swing.JTextField addProdName;
    private javax.swing.JTextField addProdPrice;
    private javax.swing.JTextField addProdQuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private javax.swing.JTextField searchProd;
    // End of variables declaration//GEN-END:variables



}
