/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjasssignment;

import javax.swing.table.DefaultTableModel;

       
public class CustomerInterface extends javax.swing.JFrame {

    User user = new User();
    Order order = new Order();
    InterfaceUpdate interUpdate = new InterfaceUpdate();
    
    
    //Constructor
    public CustomerInterface() {
        initComponents();
        order.randomId(jTextFieldInvoice);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel4 = new javax.swing.JLabel();
        Tab = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LabelProfilePhoneNum = new javax.swing.JLabel();
        LabelProfileName = new javax.swing.JLabel();
        LabelProfileAddress = new javax.swing.JLabel();
        LabelProfileEmail = new javax.swing.JLabel();
        TextFieldProfilePhoneNum = new javax.swing.JTextField();
        TextFieldProfileName = new javax.swing.JTextField();
        TextFieldProfileEmail = new javax.swing.JTextField();
        TextFieldProfileAddress = new javax.swing.JTextField();
        EditEmail = new javax.swing.JLabel();
        EditName = new javax.swing.JLabel();
        EditPhoneNum = new javax.swing.JLabel();
        EditMailingAdd = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Order = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ShowAllOrderButton = new javax.swing.JButton();
        jTextFieldUnitsProduct = new javax.swing.JTextField();
        jLabelUnits = new javax.swing.JLabel();
        jLabelTotalAmount = new javax.swing.JLabel();
        jTextFieldInvoice = new javax.swing.JTextField();
        jLabelQPrice = new javax.swing.JLabel();
        jLabelProductID = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelTotalAmount2 = new javax.swing.JLabel();
        QuantityAmountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShoppingjTable = new javax.swing.JTable();
        jLabelType = new javax.swing.JLabel();
        jLabeltype = new javax.swing.JLabel();
        jLabelProductId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelPriceProduct = new javax.swing.JLabel();
        jButtonView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Search = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LabelSearch = new javax.swing.JLabel();
        TextFiledSearch = new javax.swing.JTextField();
        ButtonSearch = new javax.swing.JButton();
        AddToOrder = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPaneSearchView = new javax.swing.JScrollPane();
        jTableSearchViewProduct = new javax.swing.JTable();
        LabelLogOut = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel4.setText("Edit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        Tab.setMinimumSize(new java.awt.Dimension(0, 0));
        Tab.setPreferredSize(new java.awt.Dimension(937, 487));

        jTextField2.setText("jTextField2");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelProfilePhoneNum.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        LabelProfilePhoneNum.setText("Phone Number");

        LabelProfileName.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        LabelProfileName.setText("Name ");

        LabelProfileAddress.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        LabelProfileAddress.setText("Address");

        LabelProfileEmail.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        LabelProfileEmail.setText("Email");

        TextFieldProfilePhoneNum.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N

        TextFieldProfileName.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        TextFieldProfileName.setFocusCycleRoot(true);

        TextFieldProfileEmail.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N

        TextFieldProfileAddress.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N

        EditEmail.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EditEmail.setText("Edit");
        EditEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditEmailMouseClicked(evt);
            }
        });

        EditName.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EditName.setText("Edit");
        EditName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditNameMouseClicked(evt);
            }
        });

        EditPhoneNum.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EditPhoneNum.setText("Edit");
        EditPhoneNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditPhoneNumMouseClicked(evt);
            }
        });

        EditMailingAdd.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        EditMailingAdd.setText("Edit");
        EditMailingAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMailingAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelProfilePhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldProfileEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(TextFieldProfilePhoneNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldProfileAddress)
                    .addComponent(TextFieldProfileName, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(EditPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EditEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditMailingAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(EditName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProfilePhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldProfilePhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditMailingAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        TextFieldProfilePhoneNum.getAccessibleContext().setAccessibleName("");
        TextFieldProfileName.getAccessibleContext().setAccessibleName("");
        TextFieldProfileEmail.getAccessibleContext().setAccessibleName("");
        TextFieldProfileAddress.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Tab.addTab("Profile", Profile);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Order.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 36)); // NOI18N
        jLabel1.setText("Order List");

        ShowAllOrderButton.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        ShowAllOrderButton.setText("Enter");
        ShowAllOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllOrderButtonActionPerformed(evt);
            }
        });

        jLabelUnits.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelUnits.setText("Units :");

        jLabelTotalAmount.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelTotalAmount.setText("Invoice :");

        jTextFieldInvoice.setText("Order ID");

        jLabelQPrice.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelQPrice.setText("Price :");

        jLabelProductID.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelProductID.setText("Product ID :");

        jLabelProductName.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelProductName.setText("Product Name :");

        jLabelTotalAmount2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelTotalAmount2.setText("Units Left : ");

        QuantityAmountLabel.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        QuantityAmountLabel.setText("Quan");

        ShoppingjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Type", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShoppingjTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ShoppingjTable);
        if (ShoppingjTable.getColumnModel().getColumnCount() > 0) {
            ShoppingjTable.getColumnModel().getColumn(0).setResizable(false);
            ShoppingjTable.getColumnModel().getColumn(1).setResizable(false);
            ShoppingjTable.getColumnModel().getColumn(2).setResizable(false);
            ShoppingjTable.getColumnModel().getColumn(3).setResizable(false);
            ShoppingjTable.getColumnModel().getColumn(4).setResizable(false);
            ShoppingjTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabelType.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelType.setText("Type : ");

        jLabeltype.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabeltype.setText("Type");

        jLabelProductId.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelProductId.setText("Id");

        jLabelName.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelName.setText("Name");

        jLabelPriceProduct.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelPriceProduct.setText("Price");

        jButtonView.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jLabel2.setText("* Click view to see total order you have");

        jLabel3.setText("* Please Enter to add to cart");

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabelProductName))
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(jLabelProductID))
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OrderLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabeltype))
                                    .addComponent(jTextFieldInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addComponent(jLabelUnits)
                                .addGap(31, 31, 31)
                                .addComponent(jTextFieldUnitsProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQPrice))
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addComponent(jLabelTotalAmount2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QuantityAmountLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowAllOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelProductId)))
                            .addGroup(OrderLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabeltype, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotalAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuantityAmountLabel)
                            .addComponent(jLabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldUnitsProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPriceProduct)
                                .addComponent(jLabel3))
                            .addComponent(jLabelQPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addComponent(jButtonView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ShowAllOrderButton)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab("Order", null, jPanel1, "");
        jPanel1.getAccessibleContext().setAccessibleName("Order");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelSearch.setFont(new java.awt.Font("Tekton Pro Cond", 0, 36)); // NOI18N
        LabelSearch.setText("Searching");

        TextFiledSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ButtonSearch.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        ButtonSearch.setText("Search");
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });

        AddToOrder.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        AddToOrder.setText("Add Order");
        AddToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToOrderActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        jTableSearchViewProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Type", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSearchViewProduct.getTableHeader().setReorderingAllowed(false);
        jScrollPaneSearchView.setViewportView(jTableSearchViewProduct);
        if (jTableSearchViewProduct.getColumnModel().getColumnCount() > 0) {
            jTableSearchViewProduct.getColumnModel().getColumn(1).setResizable(false);
            jTableSearchViewProduct.getColumnModel().getColumn(2).setResizable(false);
            jTableSearchViewProduct.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPaneSearchView)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 413, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TextFiledSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFiledSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneSearchView, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        TextFiledSearch.getAccessibleContext().setAccessibleName("Searching");

        javax.swing.GroupLayout SearchLayout = new javax.swing.GroupLayout(Search);
        Search.setLayout(SearchLayout);
        SearchLayout.setHorizontalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchLayout.setVerticalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab("Search", Search);

        LabelLogOut.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        LabelLogOut.setForeground(new java.awt.Color(51, 51, 255));
        LabelLogOut.setText("LogOut");
        LabelLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelLogOut)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Tab.getAccessibleContext().setAccessibleName("Customer Interface");
        LabelLogOut.getAccessibleContext().setAccessibleName("LogOutBtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogOutMouseClicked
        //Exit if LogOut button is triggered
        this.dispose();     
    }//GEN-LAST:event_LabelLogOutMouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTableSearchViewProduct.getModel();
        //Clear data in JTable
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void AddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToOrderActionPerformed
        //Add Order of the selected row in search
        //Select row to add order to order page

        int row = this.jTableSearchViewProduct.getSelectedRow();

        this.jLabelProductId.setText((jTableSearchViewProduct.getModel().getValueAt(row, 0)).toString());
        this.jLabelName.setText((jTableSearchViewProduct.getModel().getValueAt(row, 1)).toString());
        this.jLabeltype.setText((jTableSearchViewProduct.getModel().getValueAt(row, 2)).toString());
        this.jLabelPriceProduct.setText((jTableSearchViewProduct.getModel().getValueAt(row, 3)).toString());
        this.QuantityAmountLabel.setText((jTableSearchViewProduct.getModel().getValueAt(row, 4)).toString());

    }//GEN-LAST:event_AddToOrderActionPerformed

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTableSearchViewProduct.getModel();
        //Clear data in JTable
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        user.searchProduct(jTableSearchViewProduct, TextFiledSearch.getText());
    }//GEN-LAST:event_ButtonSearchActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        InterfaceShoppingCart shoppingCart = new InterfaceShoppingCart();
        order.compareCusId("Order.txt", TextFieldProfileName.getText(), shoppingCart.jTableShoppingCart);
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void ShowAllOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllOrderButtonActionPerformed
        order.addOrder(ShoppingjTable, jTextFieldInvoice.getText(), jLabelProductId.getText(), jLabelName.getText(), jLabeltype.getText(), jLabelPriceProduct.getText(),jTextFieldUnitsProduct.getText(), QuantityAmountLabel);
    }//GEN-LAST:event_ShowAllOrderButtonActionPerformed

    private void EditMailingAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMailingAddMouseClicked
        interUpdate.setVisible(true);
        interUpdate.pack();
        interUpdate.setLocationRelativeTo(null);
    }//GEN-LAST:event_EditMailingAddMouseClicked

    private void EditPhoneNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPhoneNumMouseClicked
        interUpdate.setVisible(true);
        interUpdate.pack();
        interUpdate.setLocationRelativeTo(null);
    }//GEN-LAST:event_EditPhoneNumMouseClicked

    private void EditNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditNameMouseClicked
        interUpdate.setVisible(true);
        interUpdate.pack();
        interUpdate.setLocationRelativeTo(null);
    }//GEN-LAST:event_EditNameMouseClicked

    private void EditEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditEmailMouseClicked
        interUpdate.setVisible(true);
        interUpdate.pack();
        interUpdate.setLocationRelativeTo(null);
    }//GEN-LAST:event_EditEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToOrder;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel EditEmail;
    private javax.swing.JLabel EditMailingAdd;
    private javax.swing.JLabel EditName;
    private javax.swing.JLabel EditPhoneNum;
    private javax.swing.JLabel LabelLogOut;
    private javax.swing.JLabel LabelProfileAddress;
    private javax.swing.JLabel LabelProfileEmail;
    private javax.swing.JLabel LabelProfileName;
    private javax.swing.JLabel LabelProfilePhoneNum;
    private javax.swing.JLabel LabelSearch;
    private javax.swing.JPanel Order;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel QuantityAmountLabel;
    private javax.swing.JPanel Search;
    private javax.swing.JTable ShoppingjTable;
    private javax.swing.JButton ShowAllOrderButton;
    private javax.swing.JTabbedPane Tab;
    public javax.swing.JTextField TextFieldProfileAddress;
    public javax.swing.JTextField TextFieldProfileEmail;
    public javax.swing.JTextField TextFieldProfileName;
    public javax.swing.JTextField TextFieldProfilePhoneNum;
    private javax.swing.JTextField TextFiledSearch;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPriceProduct;
    private javax.swing.JLabel jLabelProductID;
    private javax.swing.JLabel jLabelProductId;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelQPrice;
    private javax.swing.JLabel jLabelTotalAmount;
    private javax.swing.JLabel jLabelTotalAmount2;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelUnits;
    private javax.swing.JLabel jLabeltype;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneSearchView;
    private javax.swing.JTable jTableSearchViewProduct;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldInvoice;
    private javax.swing.JTextField jTextFieldUnitsProduct;
    // End of variables declaration//GEN-END:variables
}
